CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    salt BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS tokens (
    token VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36),
    FOREIGN KEY (user_id) REFERENCES users(id)
);